##-----------------------------------------------------------------------------
##  Copyright (C) Siemens AG 1998  All Rights Reserved.  Confidential
##-----------------------------------------------------------------------------
##
## Project: NUMARIS/4
##    File: \n4\pkg\MrServers\MrImaging\seq\a_MiniFLASH\makefile.trs
## Version:
##  Author: LANDWIPD
##  Charge: Michael Zwanger, MRIA-Seq, +9131/84-2672
##    Date: n.a. 
##
##    Lang: make
##
## Descrip: Makefile fuer Sequenz-DLL
##
##-----------------------------------------------------------------------------

##-----------------------------------------------------------------------------
## Naehere Informationen zum den moeglichen Macros im Makefile siehe
## MedMake-Dokumentation Q:/csw/MedMake/html/contents_t6.html
##
NOSYNGO() 


##-----------------------------------------------------------------------------
## enter local compiler flags
##

CPPFLAGS (-D_CONSOLE)
CPPFLAGS (-DBUILD_SEQU)
CPPFLAGS (-DSEQUENCE_CLASS)
CPPFLAGS (-DSEQUENCE_CLASS_MiniFLASH)
CPPFLAGS (-DMRPROT_DEP_OPT)
CPPFLAGS (-DSEQ_NAMESPACE=SEQ_MINIFLASH)



##-----------------------------------------------------------------------------
## enter include paths
##
INCLPATHS (-I /n4_extsw/x86/extsw/MedCom/include)



##-----------------------------------------------------------------------------
## enter source files
##
CPPSOURCES (a_MiniFLASH)
CPPSOURCES(a_MiniFLASH_UI)



##-----------------------------------------------------------------------------
## enter link libraries
##
LDLIBS (Sequence)
LDLIBS (libSBB)
LDLIBS (libSSL)
LDLIBS (libRT)
LDLIBS (SeqBuffer)
LDLIBS (libSeqUtil)
LDLIBS (libSeqUT)
LDLIBS (libUICtrl)
MSDEV_i586_WinNT400(LDLIBS (libUILink))
LDLIBS (MrProt)
LDLIBS (MeasSections)
LDLIBS (libGSL)
LDLIBS (CoilIF)
LDLIBS (MrTrace)
LDLIBS (MeasNucleiBase)
LDLIBS (libSeqSysProp)
LDLIBS (MrParc)

##-----------------------------------------------------------------------------
## enter target name
##
LIB(MiniFLASH)

##-----------------------------------------------------------------------------
##  Copyright (C) Siemens AG 1998  All Rights Reserved.  Confidential
##-----------------------------------------------------------------------------
